### ISSUE TITLE
Integrate resources from Illustrative Mathematics into the Kolibri Library

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-library#4]
## Overview 

Illustrative Mathematics have a range of resources for supporting teachers in teaching Mathematics through a project based learning framework. As such, these resources will be particularly useful for creating PBL curriculum for more general usage.

### Contributors 
- Technical lead: @rtibbles 
- Individual contributors: 
- Other relevant LE team members: 

### Goals
- [ ]  Create a channel that imports the range of Illustrative Mathematics resources in mostly PDF format
- [ ] Additionally, import Geogebra based resources for interactive Mathematics

In the future we could potentially use the HTML based resources to create more flexible, editable resources rather than PDFs.

```[tasklist]
### Tasks
- [ ] Cross reference the Illustrative Mathematics API with the channel specification sheet to determine how to map one to the other
```
